
org.gradle.jvmargs=-Xmx2G
org.gradle.java.home=/usr/local/sdkman/candidates/java/21.0.10-ms
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)

neo_version=21.1.220
neo_version_range=[21,)
loader_version_range=[4,)

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

## Mod Properties
mod_id=reskillable
mod_name=Reskillable
mod_license=MIT
mod_version=3.3.0-1.21.1
mod_group_id=reskillable
mod_authors=Bandit-Bytes
mod_description= Reskillable reimagined for 1.21.1, a mod that lets you prevent everything with skills, for the ultimate RPG Experience!!!

# Dependencies
curios_version=9.2.2